import type { Event } from "./types";

export const preEvents: Event[] = [
  {
    id: "PRE-001",
    title: "FLASH MOB 2026",
    description:
      "Registrations are now open for Kronos Flash Mob 2026.\nTraining: 6-9 April (09:00 AM - 11:00 AM).\nPerformances: 10-11 April.\nNo experience needed.",
    image: "/beyondthelens.jpeg?height=400&width=600",
    date: "Training 6-9 April, 2026 | Performances 10-11 April, 2026",
    venue: "ITM Campus",
    timing: "09:00 AM - 11:00 AM (Training)",
    category: "non-tech",
    registerLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdQKrU9ot0UkMxt2kqVxCHO2GqP_dvx_pI2-9f7LxppDdPHCw/viewform?usp=header",
    coordinator: {
      name: "Kronos Cultural Team",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-002",
    title: "KRONOS HEIST 2026",
    description:
      "A team strategy challenge designed to test pressure handling and precision.\nPrize Pool: Up to Rs 5000\nRegistration Fee: Rs 300 per team",
    image: "/escaperoom.jpeg?height=400&width=600",
    date: "10 April, 2026",
    venue: "ITM Gwalior (Sithouli)",
    timing: "TBA",
    category: "tech",
    registerLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSd__h39YWt0PSCIyOLU72yysNm-K08sNZbMgDAnB2YPkscq8g/viewform?usp=publish-editor",
    coordinator: {
      name: "Akshay Bhadauriya and Aman Preet Dubey",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "6396596865, 9162380750",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-003",
    title: "CRICKET TOURNAMENT",
    description:
      "Kronos 2026 Cricket Tournament for team play.\nPrize Pool: Rs 4100\nRegistration Fee: Rs 1100 per team",
    image: "/cricket.avif?height=400&width=600",
    date: "10-11 April, 2026",
    venue: "Football Ground, ITM Sithouli Campus",
    timing: "08:00 AM onwards",
    category: "non-tech",
    registerLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSddcI54bo6tLsqMe6YKyY0kyRe0DBgDLW5_xbjxPTldR3H_rQ/viewform?usp=header",
    coordinator: {
      name: "Event Head and Non-Tech Head",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "8103617038, 8602454476",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-004",
    title: "ARM WRESTLING",
    description:
      "Arm Wrestling Competition with two weight categories: Below 70 kg and Above 70 kg.\nPrize Pool: Up to Rs 3100\nRegistration Fee: Rs 99",
    image: "/armwrestling.jpg?height=400&width=600",
    date: "14 April, 2026",
    venue: "ITM Sithouli (Cafeteria)",
    timing: "12:00 PM",
    category: "non-tech",
    registerLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdInTLPwJ_1ZMLKf7Hz19h5G-IsJAf9s-o3wiGsSFmvkY-UDg/viewform?usp=header",
    coordinator: {
      name: "Non-Tech Head and Event Team",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "8602454476, 9369123260",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-005",
    title: "VOLLEYBALL TOURNAMENT",
    description:
      "Volleyball Tournament at Kronos 2026.\nPrize Pool: Rs 3100\nRegistration Fee: Rs 600",
    image: "/tugofwar.jpeg?height=400&width=600",
    date: "15 April, 2026",
    venue: "Volleyball Ground, ITM Gwalior",
    timing: "08:00 AM",
    category: "non-tech",
    registerLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSfkEj_51NwLDeFFRR5I4aVf5s0aVBvptFis003NaXTb7FChzg/viewform?usp=header",
    coordinator: {
      name: "Event Team",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "6260907174, 7037539857",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-006",
    title: "FOOTBALL TOURNAMENT",
    description:
      "Kronos Football Tournament with team format.\nPrize Pool: Rs 3100\nRegistration Fee: Rs 600 per team",
    image: "/football.jpeg?height=400&width=600",
    date: "16 April, 2026",
    venue: "Football Ground, ITM Campus Sithouli",
    timing: "TBA",
    category: "non-tech",
    registerLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSfTC1RHEtWkNnOeWoDOckOcNdOTueFE9nvijkgKH20O9YWHAA/viewform?usp=header",
    coordinator: {
      name: "Non-Tech Head and Event Head",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "8602454476, 9039024507",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-007",
    title: "BADMINTON TOURNAMENT",
    description:
      "Open badminton tournament.\nPrize Pool: Up to Rs 2100\nRegistration Fee: Rs 99",
    image: "/badminton.jpg?height=400&width=600",
    date: "17 April, 2026",
    venue: "Badminton Court, ITM Sithouli Campus",
    timing: "TBA",
    category: "non-tech",
    registerLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSeh7CZCyEy0jfLVTrHpNMj7__aGXmEJDmtBSDT8LbGZ64Et8A/viewform?usp=header",
    coordinator: {
      name: "Event Head and Event Co-Head",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "7415053373, 8602761311",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-008",
    title: "TUG OF WAR",
    description:
      "Team strength and coordination event.\nPrize Pool: Up to Rs 3100\nRegistration Fee: Rs 600",
    image: "/tugofwar.jpeg?height=400&width=600",
    date: "17 April, 2026",
    venue: "ITM Sithouli Cafeteria",
    timing: "12:00 PM",
    category: "non-tech",
    registerLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdnmsgogD5kqUgfzYeq7FYeFxnIFCJwlTxUcWMpqdBF6IQrXw/viewform",
    coordinator: {
      name: "Event Head and Tech Head",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "6396596865, 6260907174",
      email: "tba@kronos.in",
    },
  },
];

export const mainEvents: Event[] = [
  {
    id: "MAIN-001",
    title: "GAME DESIGNING WORKSHOP + CHARACTER FORGE",
    description:
      "Ivent'o Club workshop plus competition track.\nWorkshop: 14-16 April (09:00 AM - 11:00 AM).\nCompetition (Character Forge): 21 April (11:00 AM - 03:00 PM).\nFee: Rs 99 for complete event.",
    image: "/techtalk.jpeg?height=400&width=600",
    date: "Workshop 14-16 April, 2026 | Competition 21 April, 2026",
    venue: "ITM Gwalior Campus Labs",
    timing: "09:00 AM - 11:00 AM | 11:00 AM - 03:00 PM",
    category: "tech",
    registerLink: "https://forms.gle/uzvfsVS6nx5FecXq8",
    coordinator: {
      name: "Ivent'o Club Team",
      role: "Workshop Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-002",
    title: "KRONOS ESPORTS ARENA 2026",
    description:
      "Multigame esports arena with LAN and online formats.\nGames: Free Fire 4v4, BGMI 4v4, CODM 5v5, Valorant 2v2, Tekken 8 1v1, FIFA 25 1v1.\nPrize Pool: Up to Rs 17,999\nEntry Fees: Mobile Rs 69, Valorant Rs 99, PS Games Rs 149\nDouble elimination format with two chances for every team.",
    image: "/esports.jpeg?height=400&width=600",
    date: "18-22 April, 2026",
    venue: "ITM Gwalior, Sithouli (TFL Lab)",
    timing: "10:00 AM - 05:20 PM",
    category: "tech",
    registerLink: "https://forms.gle/qiLfHKpQehYQyhqc9",
    coordinator: {
      name: "Nikhil Shrivastava and Madhav Singh",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "7415053373, 8602761311",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-003",
    title: "HACKATHON",
    description: "Main tech hackathon track hosted over two days at IdeaPad.",
    image: "/hackathon.jpeg?height=400&width=600",
    date: "21-22 April, 2026",
    venue: "IdeaPad",
    timing: "TBA",
    category: "tech",
    registerLink: "#",
    coordinator: {
      name: "Aathrav Bhargava",
      role: "Hackathon Coordinator",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "9425705529",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-004",
    title: "ROADIES",
    description: "Main non-tech challenge event.",
    image: "/roadies.jpeg?height=400&width=600",
    date: "21 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Pushpendra and Rohit",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-005",
    title: "MOTOR SPORT",
    description: "Main non-tech motorsport event.",
    image: "/monster-dirt-bike-ergou75io6wv6bhj.jpg?height=400&width=600",
    date: "22 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Arpit",
      role: "Event Coordinator",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-006",
    title: "FASHION SHOW",
    description: "Main non-tech fashion showcase event.",
    image: "/faishonshow.jpeg?height=400&width=600",
    date: "22 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Nandini and Dev",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-007",
    title: "KRONOS COSPLAY CARNIVAL 2026",
    description:
      "Bollywood Edition cosplay event.\nEntry: Free (Open to all 1st-4th years).\nCategories: Solo, Couple, Group.\nJudging on costume, character portrayal, and stage presence.",
    image: "/cosplay.jpg?height=400&width=600",
    date: "21 April, 2026",
    venue: "Nescafe Stage",
    timing: "Starts 03:00 PM (Reporting 02:30 PM)",
    category: "non-tech",
    registerLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdPxDIbnud7bWM8C6sPUWtbUeBOf9_632LWxVEdFF-Becz_HQ/viewform?usp=header",
    coordinator: {
      name: "Kronos Cultural Team",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
];
