import type { Event } from "./types";

export const preEvents: Event[] = [
  {
    id: "PRE-001",
    title: "KRONOS HEIST",
    description:
      "Pre-event challenge mission for KRONOS 2026. Teams solve strategic tasks and advance to the main stage events.",
    image: "/escaperoom.jpeg?height=400&width=600",
    date: "7 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "tech",
    registerLink: "#",
    coordinator: {
      name: "Aman Preet and Akshay",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "9162380750",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-002",
    title: "CONTENT CREATION",
    description:
      "Pre-event content challenge focused on on-campus storytelling, reels, and creative media submissions.",
    image: "/beyondthelens.jpeg?height=400&width=600",
    date: "15-16 April, 2026",
    venue: "On Campus",
    timing: "TBA",
    category: "tech",
    registerLink: "#",
    coordinator: {
      name: "Dhruv Kumar and Jeevikaa Shivhare",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "9897209845, 6260702423",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-003",
    title: "VOLLEYBALL",
    description: "Non-tech pre-event volleyball fixture before KRONOS main event days.",
    image: "/tugofwar.jpeg?height=400&width=600",
    date: "15 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Keshav",
      role: "Event Coordinator",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-004",
    title: "BADMINTON (SINGLE)",
    description: "Non-tech pre-event singles badminton competition.",
    image: "/badminton.jpg?height=400&width=600",
    date: "14 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Antriksh Sharma",
      role: "Event Coordinator",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-005",
    title: "ARM WRESTLING",
    description: "Non-tech pre-event strength challenge in knockout format.",
    image: "/armwrestling.jpg?height=400&width=600",
    date: "13 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Gulshan Manjhi",
      role: "Event Coordinator",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-006",
    title: "FOOTBALL",
    description: "Non-tech pre-event football fixture before final KRONOS showdown days.",
    image: "/football.jpeg?height=400&width=600",
    date: "20 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Abhay Singh Jadaon",
      role: "Event Coordinator",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "PRE-007",
    title: "TUG OF WAR",
    description: "Non-tech pre-event team strength contest.",
    image: "/tugofwar.jpeg?height=400&width=600",
    date: "16 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Akshay",
      role: "Event Coordinator",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
];

export const mainEvents: Event[] = [
  {
    id: "MAIN-001",
    title: "WORKSHOP (IVENTO X ZERO ERROR) CHARACTER FORGE",
    description:
      "Main tech workshop track featuring Ivento x Zero Error Character Forge sessions across 14-16 April.",
    image: "/techtalk.jpeg?height=400&width=600",
    date: "14-16 April, 2026",
    venue: "Ground Floor Lab and Aruna Asif Ali",
    timing: "09:00 AM - 01:00 PM",
    category: "tech",
    registerLink: "#",
    coordinator: {
      name: "Tanmay and Satvik",
      role: "Workshop Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "6265235990, 7067246611",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-002",
    title: "ESPORTS",
    description:
      "Main tech esports championship with multi-day rounds in lab and NAAD venue slots.",
    image: "/esports.jpeg?height=400&width=600",
    date: "20-22 April, 2026",
    venue: "Ground Floor Lab (20-21), NAAD (22)",
    timing: "Full Day (20-21), 09:00 AM - 01:00 PM (22)",
    category: "tech",
    registerLink: "#",
    coordinator: {
      name: "Nikhil Shrivastava and Madhav Singh",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "7415053373, 8602761311",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-003",
    title: "HACKATHON",
    description: "Main tech hackathon track hosted over two days at IdeaPad.",
    image: "/hackathon.jpeg?height=400&width=600",
    date: "21-22 April, 2026",
    venue: "IdeaPad",
    timing: "TBA",
    category: "tech",
    registerLink: "#",
    coordinator: {
      name: "Aathrav Bhargava",
      role: "Hackathon Coordinator",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "9425705529",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-004",
    title: "ROADIES",
    description: "Main non-tech challenge event.",
    image: "/roadies.jpeg?height=400&width=600",
    date: "21 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Pushpendra and Rohit",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-005",
    title: "MOTOR SPORT",
    description: "Main non-tech motorsport event.",
    image: "/monster-dirt-bike-ergou75io6wv6bhj.jpg?height=400&width=600",
    date: "22 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Arpit",
      role: "Event Coordinator",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-006",
    title: "FASHION SHOW",
    description: "Main non-tech fashion showcase event.",
    image: "/faishonshow.jpeg?height=400&width=600",
    date: "22 April, 2026",
    venue: "Venue TBA",
    timing: "TBA",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Nandini and Dev",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
  {
    id: "MAIN-007",
    title: "COSPLAY",
    description: "Main non-tech cosplay showcase in evening slot.",
    image: "/cosplay.jpg?height=400&width=600",
    date: "20 April, 2026",
    venue: "Venue TBA",
    timing: "Evening",
    category: "non-tech",
    registerLink: "#",
    coordinator: {
      name: "Nandini and Dev",
      role: "Event Coordinators",
      avatar: "/placeholder.svg?height=200&width=200",
      phone: "TBA",
      email: "tba@kronos.in",
    },
  },
];
